# config @adess 06/2021
# using Tanzu Application Catalog Image https://tac.bitnami.com/apps/c1c294ea4a4a1c0c08a8d947acce0c7835aa22c2?release=sha256:205b46ecc5c0eb47cd7fbfd06b38ba24a8aee4b0aa1ae5c0ec260952d1e2cd6e

# documentation from bitnami! https://hub.docker.com/r/bitnami/mysql
FROM gcr.io/sys-2b0109it/demo/bitnami/mysql:5.7


COPY *.sql /docker-entrypoint-initdb.d/