---
- hosts: localhost
  tasks:
  - name: git install
    yum:
      name: git
    environment:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
  - name: module to clone a git repository
    environment:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
    git:
      repo: '{{git_url}}'
      dest: /var/www/html
      clone: yes
      update: yes
      version: '{{tito_release}}'
