apiVersion: v1
kind: Service
metadata:
  labels:
    run: memcached
  name: memcached
  namespace: tito-prod
spec:
  clusterIP: None  # Headless service
  ports:
  - port: 11211
    protocol: TCP
    targetPort: 11211
  selector:
    run: memcached
  

  
  selector:
    run: memcached

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
  namespace: tito-prod
spec:
  selector:
    matchLabels:
      run: memcached
  replicas: 1
  template:
    metadata:
      labels:
        run: memcached
    spec:
      containers:
      - name: memcached
        image: memcached
 #       image: gcr.io/sys-2b0109it/demo/bitnami/memcached:1
        ports:
        - containerPort: 11211
        - containerPort: 11211

