kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: default      # this is the storage class name we will create in K8s
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"  # Optional
  namespace: default
provisioner: csi.vsphere.vmware.com
allowVolumeExpansion: true
parameters:
    storagePolicyName: "vSAN Default Storage Policy" # our vSAN Storage policy from vCenter
    datastoreurl: "ds:///vmfs/volumes/vsan:a0461614ec404245-a47d30e2f329c26e/" # the Datasture-URL of our WorkloadDatastore