apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tito-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/appdess/tanzu-cloud.git
    targetRevision: HEAD
    path: tito-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: tito-prod
  syncPolicy:
    automated: {}